#pragma checksum "C:\Users\lzy\Documents\Source\LrcExt.Aurora.Music\Opportunity.LrcExt.Aurora.Music.Background\../Opportunity.LrcExt.Aurora.Music/Resources\en-us\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "7402FB6B8191B43E1F1260D8DCFEC6C4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp App { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension Extension { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage MainPage { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast Toast { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IApp : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Aurora Music Online Lyrics Extension</para>
        /// </summary>
        string DisplayName { get; }
        /// <summary>
        /// <para>Search lyrics from online databases.</para>
        /// </summary>
        string Description { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IExtension : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Online Lyrics Extension</para>
        /// </summary>
        string DisplayName { get; }
        /// <summary>
        /// <para>Search lyrics from online databases.</para>
        /// </summary>
        string Description { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IMainPage : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock DescriptionTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton InstallButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton LaunchButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton ToastToggleButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock SettingsTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock AboutTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton GithubButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton RatingButton { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IDescriptionTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>This is an extension for Aurora Music, provides lyrics from online databases include Netease Music, TT Music and ViewLyrics.</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IInstallButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Install Aurora Music</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface ILaunchButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Launch Aurora Music</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IToastToggleButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Select lyrics file manually</para>
        /// </summary>
        string Header { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface ISettingsTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Settings</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IAboutTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>About</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IGithubButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>View source at GitHub</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IRatingButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Rating and Review</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public interface IToast : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Select lyrics for</para>
        /// </summary>
        string Title { get; }
        /// <summary>
        /// <para>Select</para>
        /// </summary>
        string Select { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music
{
    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    public static class Strings
    {

        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private static global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources Resources__sObHBual;
        public static global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources Resources 
            => global::System.Threading.LazyInitializer.EnsureInitialized(ref Resources__sObHBual, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI());

        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
        private sealed class Resources__TnZfbqbI : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources
        {
            public Resources__TnZfbqbI() : base("ms-resource:///Resources/") { }


            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp App__DpS3CRfd;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.App 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.App__DpS3CRfd, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.App___OvHnib_());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class App___OvHnib_ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp
            {
                public App___OvHnib_() : base("ms-resource:///Resources/App/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/DisplayName")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp.DisplayName
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/DisplayName");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/Description")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp.Description
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/Description");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension Extension__NBVJ07V0;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.Extension 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Extension__NBVJ07V0, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.Extension__5CAerRxO());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class Extension__5CAerRxO : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension
            {
                public Extension__5CAerRxO() : base("ms-resource:///Resources/Extension/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/DisplayName")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension.DisplayName
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/DisplayName");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/Description")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension.Description
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/Description");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage MainPage__jGnLWMy8;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.MainPage 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.MainPage__jGnLWMy8, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.MainPage__sVp0yApd());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class MainPage__sVp0yApd : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage
            {
                public MainPage__sVp0yApd() : base("ms-resource:///Resources/MainPage/") { }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock DescriptionTextBlock__CEVfgoqF;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.DescriptionTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.DescriptionTextBlock__CEVfgoqF, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.MainPage__sVp0yApd.DescriptionTextBlock__xyYaYwvy());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class DescriptionTextBlock__xyYaYwvy : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock
                {
                    public DescriptionTextBlock__xyYaYwvy() : base("ms-resource:///Resources/MainPage/DescriptionTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton InstallButton__Wyk2Uu3L;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.InstallButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.InstallButton__Wyk2Uu3L, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.MainPage__sVp0yApd.InstallButton__qQLKeNHR());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class InstallButton__qQLKeNHR : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton
                {
                    public InstallButton__qQLKeNHR() : base("ms-resource:///Resources/MainPage/InstallButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/InstallButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton LaunchButton__EYtTYuX1;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.LaunchButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.LaunchButton__EYtTYuX1, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.MainPage__sVp0yApd.LaunchButton__ikaKWXyu());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class LaunchButton__ikaKWXyu : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton
                {
                    public LaunchButton__ikaKWXyu() : base("ms-resource:///Resources/MainPage/LaunchButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/LaunchButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton ToastToggleButton__FS7P7h4H;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/ToastToggleButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.ToastToggleButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.ToastToggleButton__FS7P7h4H, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.MainPage__sVp0yApd.ToastToggleButton__NNAJV8pw());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class ToastToggleButton__NNAJV8pw : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton
                {
                    public ToastToggleButton__NNAJV8pw() : base("ms-resource:///Resources/MainPage/ToastToggleButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/ToastToggleButton/Header")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton.Header
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/ToastToggleButton/Header");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock SettingsTextBlock__hXU5TtjF;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/SettingsTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.SettingsTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.SettingsTextBlock__hXU5TtjF, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.MainPage__sVp0yApd.SettingsTextBlock__kxOX_v2j());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class SettingsTextBlock__kxOX_v2j : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock
                {
                    public SettingsTextBlock__kxOX_v2j() : base("ms-resource:///Resources/MainPage/SettingsTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/SettingsTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/SettingsTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock AboutTextBlock__Mkcd1EQB;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/AboutTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.AboutTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.AboutTextBlock__Mkcd1EQB, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.MainPage__sVp0yApd.AboutTextBlock__aK_IsHD_());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class AboutTextBlock__aK_IsHD_ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock
                {
                    public AboutTextBlock__aK_IsHD_() : base("ms-resource:///Resources/MainPage/AboutTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/AboutTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/AboutTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton GithubButton___Jwng8Zp;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/GithubButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.GithubButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.GithubButton___Jwng8Zp, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.MainPage__sVp0yApd.GithubButton__xwRexjy_());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class GithubButton__xwRexjy_ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton
                {
                    public GithubButton__xwRexjy_() : base("ms-resource:///Resources/MainPage/GithubButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/GithubButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/GithubButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton RatingButton__vOX3RO4b;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/RatingButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.RatingButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.RatingButton__vOX3RO4b, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.MainPage__sVp0yApd.RatingButton__FheNr9xw());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class RatingButton__FheNr9xw : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton
                {
                    public RatingButton__FheNr9xw() : base("ms-resource:///Resources/MainPage/RatingButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/RatingButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/RatingButton/Content");
                }

            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast Toast__6b_PljP4;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.Toast 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Toast__6b_PljP4, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__TnZfbqbI.Toast__p2S_0LzW());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class Toast__p2S_0LzW : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast
            {
                public Toast__p2S_0LzW() : base("ms-resource:///Resources/Toast/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Title")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Title
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Title");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Select")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Select
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Select");
            }

        }
    }
}
