#pragma checksum "C:\Users\lzy\Documents\Source\LrcExt.Aurora.Music\Opportunity.LrcExt.Aurora.Music.Background\../Opportunity.LrcExt.Aurora.Music/Resources\en-us\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "E127D1C33655F4EFB7053E9AC60F639F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
    internal interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IApp App { get; }
        global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IExtension Extension { get; }
        global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IMainPage MainPage { get; }
        global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IToast Toast { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
    internal interface IApp : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Aurora Music Online Lyrics Extension</para>
        /// </summary>
        string DisplayName { get; }
        /// <summary>
        /// <para>Search lyrics from online databases.</para>
        /// </summary>
        string Description { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
    internal interface IExtension : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Online Lyrics Extension</para>
        /// </summary>
        string DisplayName { get; }
        /// <summary>
        /// <para>Search lyrics from online databases.</para>
        /// </summary>
        string Description { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
    internal interface IMainPage : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IDescriptionTextBlock DescriptionTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IInstallButton InstallButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.ILaunchButton LaunchButton { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
    internal interface IDescriptionTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>This is an extension for Aurora Music, provides lyrics from online databases include Netease Music, TT Music and ViewLyrics.</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
    internal interface IInstallButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Install Aurora Music</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
    internal interface ILaunchButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Launch Aurora Music</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
    internal interface IToast : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Select lyrics for</para>
        /// </summary>
        string Title { get; }
        /// <summary>
        /// <para>Select</para>
        /// </summary>
        string Select { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.Background
{
    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
    internal static class Strings
    {

        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private static global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.IResources Resources__ZWMtBNNo;
        internal static global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.IResources Resources 
            => global::System.Threading.LazyInitializer.EnsureInitialized(ref Resources__ZWMtBNNo, () => new global::Opportunity.LrcExt.Aurora.Music.Background.Strings.Resources__3dz39s3a());

        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
        private sealed class Resources__3dz39s3a : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.IResources
        {
            public Resources__3dz39s3a() : base("ms-resource:///Resources/") { }


            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IApp App__d3aYn_Hs;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App")]
            global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IApp global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.IResources.App 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.App__d3aYn_Hs, () => new global::Opportunity.LrcExt.Aurora.Music.Background.Strings.Resources__3dz39s3a.App__VQGxrAHr());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
            private sealed class App__VQGxrAHr : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IApp
            {
                public App__VQGxrAHr() : base("ms-resource:///Resources/App/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/DisplayName")]
                string global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IApp.DisplayName
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/DisplayName");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/Description")]
                string global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IApp.Description
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/Description");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IExtension Extension__nwioR1D6;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension")]
            global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IExtension global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.IResources.Extension 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Extension__nwioR1D6, () => new global::Opportunity.LrcExt.Aurora.Music.Background.Strings.Resources__3dz39s3a.Extension__UiSG_JEw());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
            private sealed class Extension__UiSG_JEw : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IExtension
            {
                public Extension__UiSG_JEw() : base("ms-resource:///Resources/Extension/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/DisplayName")]
                string global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IExtension.DisplayName
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/DisplayName");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/Description")]
                string global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IExtension.Description
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/Description");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IMainPage MainPage__J7ow2ydH;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage")]
            global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IMainPage global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.IResources.MainPage 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.MainPage__J7ow2ydH, () => new global::Opportunity.LrcExt.Aurora.Music.Background.Strings.Resources__3dz39s3a.MainPage__hUcwwuR1());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
            private sealed class MainPage__hUcwwuR1 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IMainPage
            {
                public MainPage__hUcwwuR1() : base("ms-resource:///Resources/MainPage/") { }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IDescriptionTextBlock DescriptionTextBlock__1z3qCqSp;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IDescriptionTextBlock global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IMainPage.DescriptionTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.DescriptionTextBlock__1z3qCqSp, () => new global::Opportunity.LrcExt.Aurora.Music.Background.Strings.Resources__3dz39s3a.MainPage__hUcwwuR1.DescriptionTextBlock__2eSrfb4k());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
                private sealed class DescriptionTextBlock__2eSrfb4k : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IDescriptionTextBlock
                {
                    public DescriptionTextBlock__2eSrfb4k() : base("ms-resource:///Resources/MainPage/DescriptionTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IDescriptionTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IInstallButton InstallButton__vw6xtie5;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton")]
                global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IInstallButton global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IMainPage.InstallButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.InstallButton__vw6xtie5, () => new global::Opportunity.LrcExt.Aurora.Music.Background.Strings.Resources__3dz39s3a.MainPage__hUcwwuR1.InstallButton__VGjS_WTK());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
                private sealed class InstallButton__VGjS_WTK : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IInstallButton
                {
                    public InstallButton__VGjS_WTK() : base("ms-resource:///Resources/MainPage/InstallButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.IInstallButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/InstallButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.ILaunchButton LaunchButton__vHb8PyOs;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton")]
                global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.ILaunchButton global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IMainPage.LaunchButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.LaunchButton__vHb8PyOs, () => new global::Opportunity.LrcExt.Aurora.Music.Background.Strings.Resources__3dz39s3a.MainPage__hUcwwuR1.LaunchButton__urSRI3g3());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
                private sealed class LaunchButton__urSRI3g3 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.ILaunchButton
                {
                    public LaunchButton__urSRI3g3() : base("ms-resource:///Resources/MainPage/LaunchButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.MainPage.ILaunchButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/LaunchButton/Content");
                }

            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IToast Toast__EHqih258;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast")]
            global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IToast global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.IResources.Toast 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Toast__EHqih258, () => new global::Opportunity.LrcExt.Aurora.Music.Background.Strings.Resources__3dz39s3a.Toast__hSJJhHAS());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.7.0")]
            private sealed class Toast__hSJJhHAS : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IToast
            {
                public Toast__hSJJhHAS() : base("ms-resource:///Resources/Toast/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Title")]
                string global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IToast.Title
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Title");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Select")]
                string global::Opportunity.LrcExt.Aurora.Music.Background.ResourceInfo.Resources.IToast.Select
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Select");
            }

        }
    }
}
