#pragma checksum "C:\Users\lzy\Documents\Source\LrcExt.Aurora.Music\Opportunity.LrcExt.Aurora.Music.Background\../Opportunity.LrcExt.Aurora.Music/Resources\en-us\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "F511417ACE29E254425D11E699C0A417"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp App { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension Extension { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage MainPage { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast Toast { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IApp : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Aurora Music Online Lyrics Extension</para>
        /// </summary>
        string DisplayName { get; }
        /// <summary>
        /// <para>Search lyrics from online databases.</para>
        /// </summary>
        string Description { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IExtension : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Online Lyrics Extension</para>
        /// </summary>
        string DisplayName { get; }
        /// <summary>
        /// <para>Search lyrics from online databases.</para>
        /// </summary>
        string Description { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IMainPage : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock DescriptionTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton InstallButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton LaunchButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton ToastToggleButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock SettingsTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock AboutTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton GithubButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton RatingButton { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IDescriptionTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>This is an extension for Aurora Music, provides lyrics from online databases include Netease Music, TT Music and ViewLyrics.</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IInstallButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Install Aurora Music</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface ILaunchButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Launch Aurora Music</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IToastToggleButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Select lyrics file manually</para>
        /// </summary>
        string Header { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface ISettingsTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Settings</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IAboutTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>About</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IGithubButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>View source at GitHub</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IRatingButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Rating and Review</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IToast : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Select lyrics for…</para>
        /// </summary>
        string Title { get; }
        /// <summary>
        /// <para>{title}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine1();
        /// <summary>
        /// <para>{title}</para>
        /// </summary>
        string ContentLine1(object title);
        /// <summary>
        /// <para>{title}</para>
        /// </summary>
        string ContentLine1(global::System.IFormatProvider provider, object title);
        /// <summary>
        /// <para>by {artist} in {album}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2();
        /// <summary>
        /// <para>by {artist} in {album}</para>
        /// </summary>
        string ContentLine2(object artist, object album);
        /// <summary>
        /// <para>by {artist} in {album}</para>
        /// </summary>
        string ContentLine2(global::System.IFormatProvider provider, object artist, object album);
        /// <summary>
        /// <para>in {album}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoArtist();
        /// <summary>
        /// <para>in {album}</para>
        /// </summary>
        string ContentLine2NoArtist(object album);
        /// <summary>
        /// <para>in {album}</para>
        /// </summary>
        string ContentLine2NoArtist(global::System.IFormatProvider provider, object album);
        /// <summary>
        /// <para>by {artist}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoAlbum();
        /// <summary>
        /// <para>by {artist}</para>
        /// </summary>
        string ContentLine2NoAlbum(object artist);
        /// <summary>
        /// <para>by {artist}</para>
        /// </summary>
        string ContentLine2NoAlbum(global::System.IFormatProvider provider, object artist);
        /// <summary>
        /// <para>{title} ({artist} - {album})</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString Selection();
        /// <summary>
        /// <para>{title} ({artist} - {album})</para>
        /// </summary>
        string Selection(object title, object artist, object album);
        /// <summary>
        /// <para>{title} ({artist} - {album})</para>
        /// </summary>
        string Selection(global::System.IFormatProvider provider, object title, object artist, object album);
        /// <summary>
        /// <para>{title} ({album})</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoArtist();
        /// <summary>
        /// <para>{title} ({album})</para>
        /// </summary>
        string SelectionNoArtist(object title, object album);
        /// <summary>
        /// <para>{title} ({album})</para>
        /// </summary>
        string SelectionNoArtist(global::System.IFormatProvider provider, object title, object album);
        /// <summary>
        /// <para>{title} ({artist})</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoAlbum();
        /// <summary>
        /// <para>{title} ({artist})</para>
        /// </summary>
        string SelectionNoAlbum(object title, object artist);
        /// <summary>
        /// <para>{title} ({artist})</para>
        /// </summary>
        string SelectionNoAlbum(global::System.IFormatProvider provider, object title, object artist);
        /// <summary>
        /// <para>Select</para>
        /// </summary>
        string Select { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music
{
    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal static class Strings
    {

        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private static global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources Resources__Thxi6N_v;
        internal static global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources Resources 
            => global::System.Threading.LazyInitializer.EnsureInitialized(ref Resources__Thxi6N_v, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE());

        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
        private sealed class Resources__wm1HVpYE : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources
        {
            public Resources__wm1HVpYE() : base("ms-resource:///Resources/") { }


            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp App__ZqpILtWa;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.App 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.App__ZqpILtWa, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.App__5_orMunR());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class App__5_orMunR : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp
            {
                public App__5_orMunR() : base("ms-resource:///Resources/App/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/DisplayName")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp.DisplayName
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/DisplayName");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/Description")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp.Description
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/Description");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension Extension__vD8u4Wy1;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.Extension 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Extension__vD8u4Wy1, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.Extension__ifw6r7xK());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class Extension__ifw6r7xK : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension
            {
                public Extension__ifw6r7xK() : base("ms-resource:///Resources/Extension/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/DisplayName")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension.DisplayName
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/DisplayName");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/Description")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension.Description
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/Description");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage MainPage__EWOIShAE;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.MainPage 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.MainPage__EWOIShAE, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.MainPage__PevGkd_P());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class MainPage__PevGkd_P : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage
            {
                public MainPage__PevGkd_P() : base("ms-resource:///Resources/MainPage/") { }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock DescriptionTextBlock__65SXrc2a;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.DescriptionTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.DescriptionTextBlock__65SXrc2a, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.MainPage__PevGkd_P.DescriptionTextBlock__LAgX65Cz());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class DescriptionTextBlock__LAgX65Cz : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock
                {
                    public DescriptionTextBlock__LAgX65Cz() : base("ms-resource:///Resources/MainPage/DescriptionTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton InstallButton__wQaOdvX9;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.InstallButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.InstallButton__wQaOdvX9, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.MainPage__PevGkd_P.InstallButton__yp5fFyuf());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class InstallButton__yp5fFyuf : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton
                {
                    public InstallButton__yp5fFyuf() : base("ms-resource:///Resources/MainPage/InstallButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/InstallButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton LaunchButton__ET7sNYO0;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.LaunchButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.LaunchButton__ET7sNYO0, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.MainPage__PevGkd_P.LaunchButton__CtTKeBxy());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class LaunchButton__CtTKeBxy : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton
                {
                    public LaunchButton__CtTKeBxy() : base("ms-resource:///Resources/MainPage/LaunchButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/LaunchButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton ToastToggleButton__HY8eLMdA;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/ToastToggleButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.ToastToggleButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.ToastToggleButton__HY8eLMdA, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.MainPage__PevGkd_P.ToastToggleButton__MtGve_XY());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class ToastToggleButton__MtGve_XY : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton
                {
                    public ToastToggleButton__MtGve_XY() : base("ms-resource:///Resources/MainPage/ToastToggleButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/ToastToggleButton/Header")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton.Header
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/ToastToggleButton/Header");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock SettingsTextBlock__drUTGuG7;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/SettingsTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.SettingsTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.SettingsTextBlock__drUTGuG7, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.MainPage__PevGkd_P.SettingsTextBlock__b_k36IkJ());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class SettingsTextBlock__b_k36IkJ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock
                {
                    public SettingsTextBlock__b_k36IkJ() : base("ms-resource:///Resources/MainPage/SettingsTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/SettingsTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/SettingsTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock AboutTextBlock__rpUbq_Va;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/AboutTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.AboutTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.AboutTextBlock__rpUbq_Va, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.MainPage__PevGkd_P.AboutTextBlock__6HJ3JZuO());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class AboutTextBlock__6HJ3JZuO : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock
                {
                    public AboutTextBlock__6HJ3JZuO() : base("ms-resource:///Resources/MainPage/AboutTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/AboutTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/AboutTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton GithubButton__3t4Nigkj;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/GithubButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.GithubButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.GithubButton__3t4Nigkj, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.MainPage__PevGkd_P.GithubButton__8EUQtVll());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class GithubButton__8EUQtVll : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton
                {
                    public GithubButton__8EUQtVll() : base("ms-resource:///Resources/MainPage/GithubButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/GithubButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/GithubButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton RatingButton__oRjv85OC;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/RatingButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.RatingButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.RatingButton__oRjv85OC, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.MainPage__PevGkd_P.RatingButton__Oim14r7N());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class RatingButton__Oim14r7N : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton
                {
                    public RatingButton__Oim14r7N() : base("ms-resource:///Resources/MainPage/RatingButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/RatingButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/RatingButton/Content");
                }

            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast Toast__JcQU3fdD;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.Toast 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Toast__JcQU3fdD, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__wm1HVpYE.Toast__YPf0kH0x());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class Toast__YPf0kH0x : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast
            {
                public Toast__YPf0kH0x() : base("ms-resource:///Resources/Toast/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Title")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Title
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Title");
                global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine1___MFcrTsC;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine1")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine1()
                {
                    if (ContentLine1___MFcrTsC == null)
                        ContentLine1___MFcrTsC = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine1"));
                    return ContentLine1___MFcrTsC;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine1(object title)
                {
                    if (ContentLine1___MFcrTsC == null)
                        ContentLine1___MFcrTsC = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine1"));
                    return string.Format(ContentLine1___MFcrTsC.FormatString, title);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine1(global::System.IFormatProvider provider, object title)
                {
                    if (ContentLine1___MFcrTsC == null)
                        ContentLine1___MFcrTsC = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine1"));
                    return string.Format(provider, ContentLine1___MFcrTsC.FormatString, title);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2__rl1pVOpx;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine2")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2()
                {
                    if (ContentLine2__rl1pVOpx == null)
                        ContentLine2__rl1pVOpx = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2"));
                    return ContentLine2__rl1pVOpx;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2(object artist, object album)
                {
                    if (ContentLine2__rl1pVOpx == null)
                        ContentLine2__rl1pVOpx = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2"));
                    return string.Format(ContentLine2__rl1pVOpx.FormatString, album, artist);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2(global::System.IFormatProvider provider, object artist, object album)
                {
                    if (ContentLine2__rl1pVOpx == null)
                        ContentLine2__rl1pVOpx = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2"));
                    return string.Format(provider, ContentLine2__rl1pVOpx.FormatString, album, artist);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoArtist__2czWTQnM;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine2NoArtist")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoArtist()
                {
                    if (ContentLine2NoArtist__2czWTQnM == null)
                        ContentLine2NoArtist__2czWTQnM = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoArtist"));
                    return ContentLine2NoArtist__2czWTQnM;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoArtist(object album)
                {
                    if (ContentLine2NoArtist__2czWTQnM == null)
                        ContentLine2NoArtist__2czWTQnM = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoArtist"));
                    return string.Format(ContentLine2NoArtist__2czWTQnM.FormatString, album);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoArtist(global::System.IFormatProvider provider, object album)
                {
                    if (ContentLine2NoArtist__2czWTQnM == null)
                        ContentLine2NoArtist__2czWTQnM = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoArtist"));
                    return string.Format(provider, ContentLine2NoArtist__2czWTQnM.FormatString, album);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoAlbum__av2yjlRh;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine2NoAlbum")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoAlbum()
                {
                    if (ContentLine2NoAlbum__av2yjlRh == null)
                        ContentLine2NoAlbum__av2yjlRh = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoAlbum"));
                    return ContentLine2NoAlbum__av2yjlRh;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoAlbum(object artist)
                {
                    if (ContentLine2NoAlbum__av2yjlRh == null)
                        ContentLine2NoAlbum__av2yjlRh = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoAlbum"));
                    return string.Format(ContentLine2NoAlbum__av2yjlRh.FormatString, artist);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoAlbum(global::System.IFormatProvider provider, object artist)
                {
                    if (ContentLine2NoAlbum__av2yjlRh == null)
                        ContentLine2NoAlbum__av2yjlRh = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoAlbum"));
                    return string.Format(provider, ContentLine2NoAlbum__av2yjlRh.FormatString, artist);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString Selection__cE5g22VE;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$Selection")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Selection()
                {
                    if (Selection__cE5g22VE == null)
                        Selection__cE5g22VE = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$Selection"));
                    return Selection__cE5g22VE;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Selection(object title, object artist, object album)
                {
                    if (Selection__cE5g22VE == null)
                        Selection__cE5g22VE = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$Selection"));
                    return string.Format(Selection__cE5g22VE.FormatString, album, artist, title);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Selection(global::System.IFormatProvider provider, object title, object artist, object album)
                {
                    if (Selection__cE5g22VE == null)
                        Selection__cE5g22VE = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$Selection"));
                    return string.Format(provider, Selection__cE5g22VE.FormatString, album, artist, title);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoArtist__Dlwycen9;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$SelectionNoArtist")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoArtist()
                {
                    if (SelectionNoArtist__Dlwycen9 == null)
                        SelectionNoArtist__Dlwycen9 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoArtist"));
                    return SelectionNoArtist__Dlwycen9;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoArtist(object title, object album)
                {
                    if (SelectionNoArtist__Dlwycen9 == null)
                        SelectionNoArtist__Dlwycen9 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoArtist"));
                    return string.Format(SelectionNoArtist__Dlwycen9.FormatString, album, title);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoArtist(global::System.IFormatProvider provider, object title, object album)
                {
                    if (SelectionNoArtist__Dlwycen9 == null)
                        SelectionNoArtist__Dlwycen9 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoArtist"));
                    return string.Format(provider, SelectionNoArtist__Dlwycen9.FormatString, album, title);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoAlbum__cPPd7UU1;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$SelectionNoAlbum")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoAlbum()
                {
                    if (SelectionNoAlbum__cPPd7UU1 == null)
                        SelectionNoAlbum__cPPd7UU1 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoAlbum"));
                    return SelectionNoAlbum__cPPd7UU1;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoAlbum(object title, object artist)
                {
                    if (SelectionNoAlbum__cPPd7UU1 == null)
                        SelectionNoAlbum__cPPd7UU1 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoAlbum"));
                    return string.Format(SelectionNoAlbum__cPPd7UU1.FormatString, artist, title);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoAlbum(global::System.IFormatProvider provider, object title, object artist)
                {
                    if (SelectionNoAlbum__cPPd7UU1 == null)
                        SelectionNoAlbum__cPPd7UU1 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoAlbum"));
                    return string.Format(provider, SelectionNoAlbum__cPPd7UU1.FormatString, artist, title);
                }
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Select")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Select
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Select");
            }

        }
    }
}
