#pragma checksum "C:\Users\lzy\Documents\Source\LrcExt.Aurora.Music\Opportunity.LrcExt.Aurora.Music\../Opportunity.LrcExt.Aurora.Music/Resources\en-us\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "C568F1D2BDB897EE4A7366053F0DFAB5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp App { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension Extension { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage MainPage { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast Toast { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IApp : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Aurora Music Online Lyrics Extension</para>
        /// </summary>
        string DisplayName { get; }
        /// <summary>
        /// <para>Search lyrics from online databases.</para>
        /// </summary>
        string Description { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IExtension : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Online Lyrics Extension</para>
        /// </summary>
        string DisplayName { get; }
        /// <summary>
        /// <para>Search lyrics from online databases.</para>
        /// </summary>
        string Description { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IMainPage : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock DescriptionTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton InstallButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton LaunchButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton ToastToggleButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock SettingsTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock AboutTextBlock { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton GithubButton { get; }
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton RatingButton { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IDescriptionTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>This is an extension for Aurora Music, provides lyrics from online databases include Netease Music, TT Music and ViewLyrics.</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IInstallButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Install Aurora Music</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface ILaunchButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Launch Aurora Music</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IToastToggleButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Select lyrics file manually</para>
        /// </summary>
        string Header { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface ISettingsTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Settings</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IAboutTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>About</para>
        /// </summary>
        string Text { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IGithubButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>View source at GitHub</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IRatingButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Rating and Review</para>
        /// </summary>
        string Content { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal interface IToast : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Select lyrics for</para>
        /// </summary>
        string Title { get; }
        /// <summary>
        /// <para>{title}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine1();
        /// <summary>
        /// <para>{title}</para>
        /// </summary>
        string ContentLine1(object title);
        /// <summary>
        /// <para>{title}</para>
        /// </summary>
        string ContentLine1(global::System.IFormatProvider provider, object title);
        /// <summary>
        /// <para>by {artist} in {album}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2();
        /// <summary>
        /// <para>by {artist} in {album}</para>
        /// </summary>
        string ContentLine2(object artist, object album);
        /// <summary>
        /// <para>by {artist} in {album}</para>
        /// </summary>
        string ContentLine2(global::System.IFormatProvider provider, object artist, object album);
        /// <summary>
        /// <para>in {album}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoArtist();
        /// <summary>
        /// <para>in {album}</para>
        /// </summary>
        string ContentLine2NoArtist(object album);
        /// <summary>
        /// <para>in {album}</para>
        /// </summary>
        string ContentLine2NoArtist(global::System.IFormatProvider provider, object album);
        /// <summary>
        /// <para>by {artist}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoAlbum();
        /// <summary>
        /// <para>by {artist}</para>
        /// </summary>
        string ContentLine2NoAlbum(object artist);
        /// <summary>
        /// <para>by {artist}</para>
        /// </summary>
        string ContentLine2NoAlbum(global::System.IFormatProvider provider, object artist);
        /// <summary>
        /// <para>{title} ({artist} - {album})</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString Selection();
        /// <summary>
        /// <para>{title} ({artist} - {album})</para>
        /// </summary>
        string Selection(object title, object artist, object album);
        /// <summary>
        /// <para>{title} ({artist} - {album})</para>
        /// </summary>
        string Selection(global::System.IFormatProvider provider, object title, object artist, object album);
        /// <summary>
        /// <para>{title} ({album})</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoArtist();
        /// <summary>
        /// <para>{title} ({album})</para>
        /// </summary>
        string SelectionNoArtist(object title, object album);
        /// <summary>
        /// <para>{title} ({album})</para>
        /// </summary>
        string SelectionNoArtist(global::System.IFormatProvider provider, object title, object album);
        /// <summary>
        /// <para>{title} ({artist})</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoAlbum();
        /// <summary>
        /// <para>{title} ({artist})</para>
        /// </summary>
        string SelectionNoAlbum(object title, object artist);
        /// <summary>
        /// <para>{title} ({artist})</para>
        /// </summary>
        string SelectionNoAlbum(global::System.IFormatProvider provider, object title, object artist);
        /// <summary>
        /// <para>Select</para>
        /// </summary>
        string Select { get; }
    }
}

namespace Opportunity.LrcExt.Aurora.Music
{
    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
    internal static class Strings
    {

        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private static global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources Resources__stPVicit;
        internal static global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources Resources 
            => global::System.Threading.LazyInitializer.EnsureInitialized(ref Resources__stPVicit, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae());

        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
        private sealed class Resources__5WqK5Fae : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources
        {
            public Resources__5WqK5Fae() : base("ms-resource:///Resources/") { }


            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp App__pWccw7iu;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.App 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.App__pWccw7iu, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.App__FjXZZjKQ());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class App__FjXZZjKQ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp
            {
                public App__FjXZZjKQ() : base("ms-resource:///Resources/App/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/DisplayName")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp.DisplayName
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/DisplayName");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/Description")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp.Description
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/Description");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension Extension__EOBzZqhZ;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.Extension 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Extension__EOBzZqhZ, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.Extension__u5tRxfPq());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class Extension__u5tRxfPq : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension
            {
                public Extension__u5tRxfPq() : base("ms-resource:///Resources/Extension/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/DisplayName")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension.DisplayName
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/DisplayName");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/Description")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension.Description
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/Description");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage MainPage__3sh82wtc;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.MainPage 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.MainPage__3sh82wtc, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.MainPage__CQky5o0Q());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class MainPage__CQky5o0Q : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage
            {
                public MainPage__CQky5o0Q() : base("ms-resource:///Resources/MainPage/") { }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock DescriptionTextBlock__KiGy2ym6;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.DescriptionTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.DescriptionTextBlock__KiGy2ym6, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.MainPage__CQky5o0Q.DescriptionTextBlock__3U0xbVMv());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class DescriptionTextBlock__3U0xbVMv : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock
                {
                    public DescriptionTextBlock__3U0xbVMv() : base("ms-resource:///Resources/MainPage/DescriptionTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton InstallButton__ObCMgF0p;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.InstallButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.InstallButton__ObCMgF0p, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.MainPage__CQky5o0Q.InstallButton__Te3f6nnn());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class InstallButton__Te3f6nnn : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton
                {
                    public InstallButton__Te3f6nnn() : base("ms-resource:///Resources/MainPage/InstallButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/InstallButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton LaunchButton__Mt_Q9Oem;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.LaunchButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.LaunchButton__Mt_Q9Oem, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.MainPage__CQky5o0Q.LaunchButton__Xr_aDOTv());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class LaunchButton__Xr_aDOTv : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton
                {
                    public LaunchButton__Xr_aDOTv() : base("ms-resource:///Resources/MainPage/LaunchButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/LaunchButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton ToastToggleButton__pi3fd5mg;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/ToastToggleButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.ToastToggleButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.ToastToggleButton__pi3fd5mg, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.MainPage__CQky5o0Q.ToastToggleButton__uKKNQzyG());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class ToastToggleButton__uKKNQzyG : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton
                {
                    public ToastToggleButton__uKKNQzyG() : base("ms-resource:///Resources/MainPage/ToastToggleButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/ToastToggleButton/Header")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton.Header
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/ToastToggleButton/Header");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock SettingsTextBlock__0F3wCA_T;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/SettingsTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.SettingsTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.SettingsTextBlock__0F3wCA_T, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.MainPage__CQky5o0Q.SettingsTextBlock__MPRPlKJa());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class SettingsTextBlock__MPRPlKJa : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock
                {
                    public SettingsTextBlock__MPRPlKJa() : base("ms-resource:///Resources/MainPage/SettingsTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/SettingsTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/SettingsTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock AboutTextBlock__KlgFOTHX;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/AboutTextBlock")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.AboutTextBlock 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.AboutTextBlock__KlgFOTHX, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.MainPage__CQky5o0Q.AboutTextBlock__VR09wqhK());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class AboutTextBlock__VR09wqhK : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock
                {
                    public AboutTextBlock__VR09wqhK() : base("ms-resource:///Resources/MainPage/AboutTextBlock/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/AboutTextBlock/Text")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock.Text
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/AboutTextBlock/Text");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton GithubButton__SeYlOdvw;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/GithubButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.GithubButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.GithubButton__SeYlOdvw, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.MainPage__CQky5o0Q.GithubButton__WvV0Bdkv());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class GithubButton__WvV0Bdkv : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton
                {
                    public GithubButton__WvV0Bdkv() : base("ms-resource:///Resources/MainPage/GithubButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/GithubButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/GithubButton/Content");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton RatingButton__trCT_u4e;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/RatingButton")]
                global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.RatingButton 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.RatingButton__trCT_u4e, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.MainPage__CQky5o0Q.RatingButton__oJ49NSSJ());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
                private sealed class RatingButton__oJ49NSSJ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton
                {
                    public RatingButton__oJ49NSSJ() : base("ms-resource:///Resources/MainPage/RatingButton/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/RatingButton/Content")]
                    string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/RatingButton/Content");
                }

            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast Toast__mvfCdzqs;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.Toast 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Toast__mvfCdzqs, () => new global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__5WqK5Fae.Toast__SeSElUxB());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.8.0")]
            private sealed class Toast__SeSElUxB : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast
            {
                public Toast__SeSElUxB() : base("ms-resource:///Resources/Toast/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Title")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Title
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Title");
                global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine1__5sqEwL4o;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine1")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine1()
                {
                    if (ContentLine1__5sqEwL4o == null)
                        ContentLine1__5sqEwL4o = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine1"));
                    return ContentLine1__5sqEwL4o;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine1(object title)
                {
                    if (ContentLine1__5sqEwL4o == null)
                        ContentLine1__5sqEwL4o = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine1"));
                    return string.Format(ContentLine1__5sqEwL4o.FormatString, title);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine1(global::System.IFormatProvider provider, object title)
                {
                    if (ContentLine1__5sqEwL4o == null)
                        ContentLine1__5sqEwL4o = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine1"));
                    return string.Format(provider, ContentLine1__5sqEwL4o.FormatString, title);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2__bRxCTCEK;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine2")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2()
                {
                    if (ContentLine2__bRxCTCEK == null)
                        ContentLine2__bRxCTCEK = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2"));
                    return ContentLine2__bRxCTCEK;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2(object artist, object album)
                {
                    if (ContentLine2__bRxCTCEK == null)
                        ContentLine2__bRxCTCEK = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2"));
                    return string.Format(ContentLine2__bRxCTCEK.FormatString, album, artist);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2(global::System.IFormatProvider provider, object artist, object album)
                {
                    if (ContentLine2__bRxCTCEK == null)
                        ContentLine2__bRxCTCEK = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2"));
                    return string.Format(provider, ContentLine2__bRxCTCEK.FormatString, album, artist);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoArtist__DPQze4KB;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine2NoArtist")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoArtist()
                {
                    if (ContentLine2NoArtist__DPQze4KB == null)
                        ContentLine2NoArtist__DPQze4KB = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoArtist"));
                    return ContentLine2NoArtist__DPQze4KB;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoArtist(object album)
                {
                    if (ContentLine2NoArtist__DPQze4KB == null)
                        ContentLine2NoArtist__DPQze4KB = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoArtist"));
                    return string.Format(ContentLine2NoArtist__DPQze4KB.FormatString, album);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoArtist(global::System.IFormatProvider provider, object album)
                {
                    if (ContentLine2NoArtist__DPQze4KB == null)
                        ContentLine2NoArtist__DPQze4KB = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoArtist"));
                    return string.Format(provider, ContentLine2NoArtist__DPQze4KB.FormatString, album);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoAlbum__Q18HVrv1;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine2NoAlbum")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoAlbum()
                {
                    if (ContentLine2NoAlbum__Q18HVrv1 == null)
                        ContentLine2NoAlbum__Q18HVrv1 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoAlbum"));
                    return ContentLine2NoAlbum__Q18HVrv1;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoAlbum(object artist)
                {
                    if (ContentLine2NoAlbum__Q18HVrv1 == null)
                        ContentLine2NoAlbum__Q18HVrv1 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoAlbum"));
                    return string.Format(ContentLine2NoAlbum__Q18HVrv1.FormatString, artist);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoAlbum(global::System.IFormatProvider provider, object artist)
                {
                    if (ContentLine2NoAlbum__Q18HVrv1 == null)
                        ContentLine2NoAlbum__Q18HVrv1 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoAlbum"));
                    return string.Format(provider, ContentLine2NoAlbum__Q18HVrv1.FormatString, artist);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString Selection__q7SZ5J7k;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$Selection")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Selection()
                {
                    if (Selection__q7SZ5J7k == null)
                        Selection__q7SZ5J7k = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$Selection"));
                    return Selection__q7SZ5J7k;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Selection(object title, object artist, object album)
                {
                    if (Selection__q7SZ5J7k == null)
                        Selection__q7SZ5J7k = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$Selection"));
                    return string.Format(Selection__q7SZ5J7k.FormatString, album, artist, title);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Selection(global::System.IFormatProvider provider, object title, object artist, object album)
                {
                    if (Selection__q7SZ5J7k == null)
                        Selection__q7SZ5J7k = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$Selection"));
                    return string.Format(provider, Selection__q7SZ5J7k.FormatString, album, artist, title);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoArtist__LihkkE9Z;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$SelectionNoArtist")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoArtist()
                {
                    if (SelectionNoArtist__LihkkE9Z == null)
                        SelectionNoArtist__LihkkE9Z = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoArtist"));
                    return SelectionNoArtist__LihkkE9Z;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoArtist(object title, object album)
                {
                    if (SelectionNoArtist__LihkkE9Z == null)
                        SelectionNoArtist__LihkkE9Z = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoArtist"));
                    return string.Format(SelectionNoArtist__LihkkE9Z.FormatString, album, title);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoArtist(global::System.IFormatProvider provider, object title, object album)
                {
                    if (SelectionNoArtist__LihkkE9Z == null)
                        SelectionNoArtist__LihkkE9Z = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoArtist"));
                    return string.Format(provider, SelectionNoArtist__LihkkE9Z.FormatString, album, title);
                }
                global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoAlbum__BfXxaozS;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$SelectionNoAlbum")]
                global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoAlbum()
                {
                    if (SelectionNoAlbum__BfXxaozS == null)
                        SelectionNoAlbum__BfXxaozS = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoAlbum"));
                    return SelectionNoAlbum__BfXxaozS;
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoAlbum(object title, object artist)
                {
                    if (SelectionNoAlbum__BfXxaozS == null)
                        SelectionNoAlbum__BfXxaozS = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoAlbum"));
                    return string.Format(SelectionNoAlbum__BfXxaozS.FormatString, artist, title);
                }
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoAlbum(global::System.IFormatProvider provider, object title, object artist)
                {
                    if (SelectionNoAlbum__BfXxaozS == null)
                        SelectionNoAlbum__BfXxaozS = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoAlbum"));
                    return string.Format(provider, SelectionNoAlbum__BfXxaozS.FormatString, artist, title);
                }
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Select")]
                string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Select
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Select");
            }

        }
    }
}
