#pragma checksum "C:\Users\lzy\Documents\Sources\OpportunityLiu\LrcExt.Aurora.Music\Opportunity.LrcExt.Aurora.Music\../Opportunity.LrcExt.Aurora.Music/Resources\en-us\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "8AFC553CE80651509BD75163928617B6"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo {
    
    
    /// <summary><para>Path: ms-resource:///Resources</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/App</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp App {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/Extension</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension Extension {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage MainPage {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/Toast</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast Toast {
            get;
        }
    }
}
namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources {
    
    
    /// <summary><para>Path: ms-resource:///Resources/App</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IApp : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/App/DisplayName</para><para>Value:</para><para>Aurora Music Online Lyrics Extension</para></summary>
        string DisplayName {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/App/Description</para><para>Value:</para><para>Search lyrics from online databases.</para></summary>
        string Description {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/Extension</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IExtension : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/Extension/DisplayName</para><para>Value:</para><para>Online Lyrics Extension</para></summary>
        string DisplayName {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/Extension/Description</para><para>Value:</para><para>Search lyrics from online databases.</para></summary>
        string Description {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/MainPage</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IMainPage : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/DescriptionTextBlock</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock DescriptionTextBlock {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/InstallButton</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton InstallButton {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/LaunchButton</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton LaunchButton {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/ToastToggleButton</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton ToastToggleButton {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/SettingsTextBlock</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock SettingsTextBlock {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/AboutTextBlock</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock AboutTextBlock {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/GithubButton</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton GithubButton {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/RatingButton</para></summary>
        global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton RatingButton {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/Toast</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IToast : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/Title</para><para>Value:</para><para>Select lyrics for…</para></summary>
        string Title {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/Select</para><para>Value:</para><para>Select</para></summary>
        string Select {
            get;
        }
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine1</para><para>Value:</para><para>{title}</para></summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine1();
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine1</para><para>Value:</para><para>{title}</para></summary>
        string ContentLine1(object title);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine1</para><para>Value:</para><para>{title}</para></summary>
        string ContentLine1(global::System.IFormatProvider provider, object title);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine2</para><para>Value:</para><para>by {artist} in {album}</para></summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2();
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine2</para><para>Value:</para><para>by {artist} in {album}</para></summary>
        string ContentLine2(object artist, object album);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine2</para><para>Value:</para><para>by {artist} in {album}</para></summary>
        string ContentLine2(global::System.IFormatProvider provider, object artist, object album);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine2NoArtist</para><para>Value:</para><para>in {album}</para></summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoArtist();
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine2NoArtist</para><para>Value:</para><para>in {album}</para></summary>
        string ContentLine2NoArtist(object album);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine2NoArtist</para><para>Value:</para><para>in {album}</para></summary>
        string ContentLine2NoArtist(global::System.IFormatProvider provider, object album);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine2NoAlbum</para><para>Value:</para><para>by {artist}</para></summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoAlbum();
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine2NoAlbum</para><para>Value:</para><para>by {artist}</para></summary>
        string ContentLine2NoAlbum(object artist);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$ContentLine2NoAlbum</para><para>Value:</para><para>by {artist}</para></summary>
        string ContentLine2NoAlbum(global::System.IFormatProvider provider, object artist);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$Selection</para><para>Value:</para><para>{title} ({artist} - {album})</para></summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString Selection();
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$Selection</para><para>Value:</para><para>{title} ({artist} - {album})</para></summary>
        string Selection(object title, object artist, object album);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$Selection</para><para>Value:</para><para>{title} ({artist} - {album})</para></summary>
        string Selection(global::System.IFormatProvider provider, object title, object artist, object album);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$SelectionNoArtist</para><para>Value:</para><para>{title} ({album})</para></summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoArtist();
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$SelectionNoArtist</para><para>Value:</para><para>{title} ({album})</para></summary>
        string SelectionNoArtist(object title, object album);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$SelectionNoArtist</para><para>Value:</para><para>{title} ({album})</para></summary>
        string SelectionNoArtist(global::System.IFormatProvider provider, object title, object album);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$SelectionNoAlbum</para><para>Value:</para><para>{title} ({artist})</para></summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoAlbum();
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$SelectionNoAlbum</para><para>Value:</para><para>{title} ({artist})</para></summary>
        string SelectionNoAlbum(object title, object artist);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$SelectionNoAlbum</para><para>Value:</para><para>{title} ({artist})</para></summary>
        string SelectionNoAlbum(global::System.IFormatProvider provider, object title, object artist);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$SelectionTitleOnly</para><para>Value:</para><para>{title}</para></summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString SelectionTitleOnly();
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$SelectionTitleOnly</para><para>Value:</para><para>{title}</para></summary>
        string SelectionTitleOnly(object title);
        
        /// <summary><para>Path: ms-resource:///Resources/Toast/$SelectionTitleOnly</para><para>Value:</para><para>{title}</para></summary>
        string SelectionTitleOnly(global::System.IFormatProvider provider, object title);
    }
}
namespace Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage {
    
    
    /// <summary><para>Path: ms-resource:///Resources/MainPage/DescriptionTextBlock</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IDescriptionTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/DescriptionTextBlock/Text</para><para>Value:</para><para>This is an extension for Aurora Music, provides lyrics from online databases include Netease Music, QQ Music, TT Music and ViewLyrics.</para></summary>
        string Text {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/MainPage/InstallButton</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IInstallButton : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/InstallButton/Content</para><para>Value:</para><para>Install Aurora Music</para></summary>
        string Content {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/MainPage/LaunchButton</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface ILaunchButton : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/LaunchButton/Content</para><para>Value:</para><para>Launch Aurora Music</para></summary>
        string Content {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/MainPage/ToastToggleButton</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IToastToggleButton : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/ToastToggleButton/Header</para><para>Value:</para><para>Select lyrics file manually</para></summary>
        string Header {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/MainPage/SettingsTextBlock</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface ISettingsTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/SettingsTextBlock/Text</para><para>Value:</para><para>Settings</para></summary>
        string Text {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/MainPage/AboutTextBlock</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IAboutTextBlock : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/AboutTextBlock/Text</para><para>Value:</para><para>About</para></summary>
        string Text {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/MainPage/GithubButton</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IGithubButton : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/GithubButton/Content</para><para>Value:</para><para>View source at GitHub</para></summary>
        string Content {
            get;
        }
    }
    
    /// <summary><para>Path: ms-resource:///Resources/MainPage/RatingButton</para></summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    internal interface IRatingButton : global::Opportunity.ResourceGenerator.IResourceProvider {
        
        /// <summary><para>Path: ms-resource:///Resources/MainPage/RatingButton/Content</para><para>Value:</para><para>Rating and Review</para></summary>
        string Content {
            get;
        }
    }
}
namespace Opportunity.LrcExt.Aurora.Music {
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal sealed class Strings {
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__mwkMzs8q s_Resources__yMjttifl;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.App__XZfYn5qZ s_App__YR7FwwlK;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.Extension__aqiB5Y_V s_Extension__QaKwAxb7;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.MainPage__K3lfioqS s_MainPage__sjIHDNpI;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.DescriptionTextBlock__ArsROM0p s_DescriptionTextBlock__mdj_wmMn;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.InstallButton__qOM4V3WF s_InstallButton__NFqA3XQh;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.LaunchButton__OteUMhDW s_LaunchButton__Ql3OOeLT;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.ToastToggleButton__hAjUh2o9 s_ToastToggleButton___2gVN_Km;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.SettingsTextBlock__WVu9gth_ s_SettingsTextBlock__xyVH8P72;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.AboutTextBlock__lWbHKX8G s_AboutTextBlock__WW4AZNJs;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.GithubButton__sK3wQ_EL s_GithubButton__CwL17di1;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.RatingButton__Gb_ETnK9 s_RatingButton__jJQK3vED;
        
        private static global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z s_Toast__pvSIUdIr;
        
        private Strings() {
        }
        
        internal static global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources Resources {
            get {
                return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.Resources__mwkMzs8q>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_Resources__yMjttifl);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class Resources__mwkMzs8q : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources {
            
            public Resources__mwkMzs8q() : 
                    base("ms-resource:///Resources/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.App {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.App__XZfYn5qZ>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_App__YR7FwwlK);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.Extension {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.Extension__aqiB5Y_V>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_Extension__QaKwAxb7);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.MainPage {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.MainPage__K3lfioqS>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_MainPage__sjIHDNpI);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.IResources.Toast {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_Toast__pvSIUdIr);
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class App__XZfYn5qZ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp {
            
            public App__XZfYn5qZ() : 
                    base("ms-resource:///Resources/App/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/DisplayName")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp.DisplayName {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/DisplayName");
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/Description")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IApp.Description {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/Description");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class Extension__aqiB5Y_V : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension {
            
            public Extension__aqiB5Y_V() : 
                    base("ms-resource:///Resources/Extension/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/DisplayName")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension.DisplayName {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/DisplayName");
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extension/Description")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IExtension.Description {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extension/Description");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class MainPage__K3lfioqS : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage {
            
            public MainPage__K3lfioqS() : 
                    base("ms-resource:///Resources/MainPage/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.DescriptionTextBlock {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.DescriptionTextBlock__ArsROM0p>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_DescriptionTextBlock__mdj_wmMn);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.InstallButton {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.InstallButton__qOM4V3WF>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_InstallButton__NFqA3XQh);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.LaunchButton {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.LaunchButton__OteUMhDW>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_LaunchButton__Ql3OOeLT);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/ToastToggleButton")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.ToastToggleButton {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.ToastToggleButton__hAjUh2o9>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_ToastToggleButton___2gVN_Km);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/SettingsTextBlock")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.SettingsTextBlock {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.SettingsTextBlock__WVu9gth_>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_SettingsTextBlock__xyVH8P72);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/AboutTextBlock")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.AboutTextBlock {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.AboutTextBlock__lWbHKX8G>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_AboutTextBlock__WW4AZNJs);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/GithubButton")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.GithubButton {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.GithubButton__sK3wQ_EL>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_GithubButton__CwL17di1);
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/RatingButton")]
            global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IMainPage.RatingButton {
                get {
                    return System.Threading.LazyInitializer.EnsureInitialized<global::Opportunity.LrcExt.Aurora.Music.Strings.RatingButton__Gb_ETnK9>(ref global::Opportunity.LrcExt.Aurora.Music.Strings.s_RatingButton__jJQK3vED);
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class DescriptionTextBlock__ArsROM0p : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock {
            
            public DescriptionTextBlock__ArsROM0p() : 
                    base("ms-resource:///Resources/MainPage/DescriptionTextBlock/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IDescriptionTextBlock.Text {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/DescriptionTextBlock/Text");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class InstallButton__qOM4V3WF : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton {
            
            public InstallButton__qOM4V3WF() : 
                    base("ms-resource:///Resources/MainPage/InstallButton/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/InstallButton/Content")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IInstallButton.Content {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/InstallButton/Content");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class LaunchButton__OteUMhDW : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton {
            
            public LaunchButton__OteUMhDW() : 
                    base("ms-resource:///Resources/MainPage/LaunchButton/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/LaunchButton/Content")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ILaunchButton.Content {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/LaunchButton/Content");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class ToastToggleButton__hAjUh2o9 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton {
            
            public ToastToggleButton__hAjUh2o9() : 
                    base("ms-resource:///Resources/MainPage/ToastToggleButton/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/ToastToggleButton/Header")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IToastToggleButton.Header {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/ToastToggleButton/Header");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class SettingsTextBlock__WVu9gth_ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock {
            
            public SettingsTextBlock__WVu9gth_() : 
                    base("ms-resource:///Resources/MainPage/SettingsTextBlock/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/SettingsTextBlock/Text")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.ISettingsTextBlock.Text {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/SettingsTextBlock/Text");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class AboutTextBlock__lWbHKX8G : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock {
            
            public AboutTextBlock__lWbHKX8G() : 
                    base("ms-resource:///Resources/MainPage/AboutTextBlock/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/AboutTextBlock/Text")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IAboutTextBlock.Text {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/AboutTextBlock/Text");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class GithubButton__sK3wQ_EL : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton {
            
            public GithubButton__sK3wQ_EL() : 
                    base("ms-resource:///Resources/MainPage/GithubButton/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/GithubButton/Content")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IGithubButton.Content {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/GithubButton/Content");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class RatingButton__Gb_ETnK9 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton {
            
            public RatingButton__Gb_ETnK9() : 
                    base("ms-resource:///Resources/MainPage/RatingButton/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/MainPage/RatingButton/Content")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.MainPage.IRatingButton.Content {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/MainPage/RatingButton/Content");
                }
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")]
        private sealed class Toast__ddLoDt5z : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast {
            
            private static global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine1__j4NEPOT7 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine1"));
            
            private static global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2__AKiNEhDA = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2"));
            
            private static global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoArtist__gQr8Q9g9 = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoArtist"));
            
            private static global::Opportunity.ResourceGenerator.FormattableResourceString ContentLine2NoAlbum__YdG77M0O = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$ContentLine2NoAlbum"));
            
            private static global::Opportunity.ResourceGenerator.FormattableResourceString Selection__IvwjgUfj = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$Selection"));
            
            private static global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoArtist__LMftWb7u = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoArtist"));
            
            private static global::Opportunity.ResourceGenerator.FormattableResourceString SelectionNoAlbum__eVCwDt5J = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionNoAlbum"));
            
            private static global::Opportunity.ResourceGenerator.FormattableResourceString SelectionTitleOnly__dWPCKI3U = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/$SelectionTitleOnly"));
            
            public Toast__ddLoDt5z() : 
                    base("ms-resource:///Resources/Toast/") {
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Title")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Title {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Title");
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/Select")]
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Select {
                get {
                    return global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Toast/Select");
                }
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine1")]
            global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine1() {
                return global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine1__j4NEPOT7;
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine1(object title) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine1__j4NEPOT7.FormatString, title);
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine1(global::System.IFormatProvider provider, object title) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine1__j4NEPOT7.FormatString, provider, title);
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine2")]
            global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2() {
                return global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine2__AKiNEhDA;
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2(object artist, object album) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine2__AKiNEhDA.FormatString, album, artist);
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2(global::System.IFormatProvider provider, object artist, object album) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine2__AKiNEhDA.FormatString, provider, album, artist);
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine2NoArtist")]
            global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoArtist() {
                return global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine2NoArtist__gQr8Q9g9;
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoArtist(object album) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine2NoArtist__gQr8Q9g9.FormatString, album);
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoArtist(global::System.IFormatProvider provider, object album) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine2NoArtist__gQr8Q9g9.FormatString, provider, album);
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$ContentLine2NoAlbum")]
            global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoAlbum() {
                return global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine2NoAlbum__YdG77M0O;
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoAlbum(object artist) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine2NoAlbum__YdG77M0O.FormatString, artist);
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.ContentLine2NoAlbum(global::System.IFormatProvider provider, object artist) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.ContentLine2NoAlbum__YdG77M0O.FormatString, provider, artist);
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$Selection")]
            global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Selection() {
                return global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.Selection__IvwjgUfj;
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Selection(object title, object artist, object album) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.Selection__IvwjgUfj.FormatString, album, artist, title);
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.Selection(global::System.IFormatProvider provider, object title, object artist, object album) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.Selection__IvwjgUfj.FormatString, provider, album, artist, title);
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$SelectionNoArtist")]
            global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoArtist() {
                return global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.SelectionNoArtist__LMftWb7u;
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoArtist(object title, object album) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.SelectionNoArtist__LMftWb7u.FormatString, album, title);
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoArtist(global::System.IFormatProvider provider, object title, object album) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.SelectionNoArtist__LMftWb7u.FormatString, provider, album, title);
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$SelectionNoAlbum")]
            global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoAlbum() {
                return global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.SelectionNoAlbum__eVCwDt5J;
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoAlbum(object title, object artist) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.SelectionNoAlbum__eVCwDt5J.FormatString, artist, title);
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionNoAlbum(global::System.IFormatProvider provider, object title, object artist) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.SelectionNoAlbum__eVCwDt5J.FormatString, provider, artist, title);
            }
            
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Toast/$SelectionTitleOnly")]
            global::Opportunity.ResourceGenerator.FormattableResourceString global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionTitleOnly() {
                return global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.SelectionTitleOnly__dWPCKI3U;
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionTitleOnly(object title) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.SelectionTitleOnly__dWPCKI3U.FormatString, title);
            }
            
            string global::Opportunity.LrcExt.Aurora.Music.ResourceInfo.Resources.IToast.SelectionTitleOnly(global::System.IFormatProvider provider, object title) {
                return string.Format(global::Opportunity.LrcExt.Aurora.Music.Strings.Toast__ddLoDt5z.SelectionTitleOnly__dWPCKI3U.FormatString, provider, title);
            }
        }
    }
}
